const loginFields = [
  {
    labelText: "Student ID",
    labelFor: "studentID",
    id: "StudentID",
    name: "StuID",
    type: "tel",
    autoComplete: "tel",
    isRequired: true,
    placeholder: "Student ID",
    maxLength: "8",
    minLength: "8",
    pattern: "[0-9]+",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
];

const signupFields = [
  {
    labelText: "StudentID",
    labelFor: "StudentID",
    id: "StudentID",
    name: "StudentID",
    type: "text",
    autoComplete: "StudentID",
    isRequired: true,
    placeholder: "Student ID",
    maxLength: "8",
    minLength: "8",
    pattern: "[0-9]+",
  },
  {
    labelText: "Email address",
    labelFor: "emailAddress",
    id: "emailAddress",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email address",
  },
  {
    labelText: "Full Name",
    labelFor: "fullName",
    id: "fullName",
    name: "fullname",
    type: "text",
    autoComplete: "text",
    isRequired: true,
    placeholder: "Full Name",
  },
  {
    labelText: "dateOfBirth",
    labelFor: "dateOfBirth",
    id: "dateOfBirth",
    name: "Date of birth",
    type: "date",
    autoComplete: "date",
    isRequired: true,
    placeholder: "Date of birth",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
  {
    labelText: "Confirm Password",
    labelFor: "confirmPassword",
    id: "confirmPassword",
    name: "confirmPassword",
    type: "password",
    isRequired: true,
    placeholder: "Confirm Password",
  },
];

export { loginFields, signupFields };
